### ISSUE TITLE
Undo and Reset buttons are incorrectly displayed when using forced unicode fonts

### ISSUE THREAD

**Issue by NightSharp** [r8420/MoreOverlays-updated#26]
MC-1.18.2-Forge-40.0.32
Configured-1.5.3
MoreOverlays_updated-1.20.5

The Game says the Config Screen is Broken, like this
![屏幕截图 2022-03-30 052046](https://user-images.githubusercontent.com/9748063/160709778-6ffdff83-64b0-4236-9c00-3dde519390b9.png)

The whole screen is like this
![2022-03-30_05 26 40](https://user-images.githubusercontent.com/9748063/160710095-98f86bd6-e259-4c39-ba60-6e54807988c5.png)

Is it able to be fixed?

**Comment by r8420** [comment]
This mod doesn't use the Configured mod and has it's own implementation of a config screen. The code is very outdated and needs to be rewritten, that will take some time.

**Comment by r8420** [comment]
Should be fixed in the latest version

**Comment by NightSharp** [comment]
> Should be fixed in the latest version

There still exists some mismatch in the bottom
![屏幕截图 2022-08-09 140753](https://user-images.githubusercontent.com/9748063/183577053-5a3f7d77-e3e4-40b3-9ddc-2faae8e38653.png)
